  version: '3'
  services:
    app:
      container_name: quiz
      build: .
      ports:
        - 8080:8080
      restart: on-failure
      depends_on:
        - fullstack-postgres          # Uncomment this when using postgres.
        # - fullstack-mysql           # Uncomment this when using mysql.
      networks:
        - fullstack


    fullstack-postgres:
      image: postgres:latest
      container_name: full_db_postgres
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
        - DATABASE_HOST=${DB_HOST}
      ports:
        - '5432:5432'
      networks:
        - fullstack

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin_container
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      depends_on:
        - fullstack-postgres
      ports:
        - "5050:80"
      networks:
        - fullstack
      restart: unless-stopped

  networks:
    fullstack:
      driver: bridge