
######################################
#
# Add proto gen stage
#
######################################

######################################
#
# Add wire gen stage
#
######################################

######################################
#
# Compliation build stage
#
######################################

FROM golang:1.13-alpine3.11 as builder

RUN apk update && apk add --no-cache git

RUN mkdir /src
WORKDIR /src

RUN apk add --update --no-cache --repository https://dl-4.alpinelinux.org/alpine/latest-stable/community/ make git

ADD . /src

RUN make deps

WORKDIR /src/main

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./main .

EXPOSE 8080

ENTRYPOINT ["./main"]

