  version: '3'
  services:
    full_db_postgres:
      image: postgres:latest
      container_name: full_db_postgres
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
        - DATABASE_HOST=${DB_HOST}
      ports:
        - '5432:5432'
      networks:
        - quiz

    migration:
      container_name: quiz-migration
      build:
        context: ./
        dockerfile: Dockerfile-migration
      restart: on-failure
      links:
        - full_db_postgres
      networks:
        - quiz
    app:
      container_name: app
      build:
        context: ./
        dockerfile: Dockerfile-app
      restart: on-failure
      depends_on:
        - migration
      networks:
        - quiz

    nginx:
      build:
        context: ./
        dockerfile: Dockerfile-nginx
      ports:
        - "80:80"
      depends_on:
        - app
      links:
        - app
      networks:
        - quiz

  networks:
    quiz:
      driver: bridge
