
######################################
#
# Compilation build stage
#
######################################

FROM golang:1.13-alpine3.11 as builder

RUN apk update && apk add --no-cache git

RUN mkdir /src

ADD . /src

RUN apk add --update --no-cache --repository https://dl-4.alpinelinux.org/alpine/latest-stable/community/ make git

WORKDIR /src

RUN CGO_ENABLED=0 GOOS=linux make wire-generate-docker

WORKDIR /src/cmd

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./main .

ENTRYPOINT ["./main", "up"]
