
######################################
#
# Compilation build stage
#
######################################

FROM golang as builder

RUN mkdir /src

ADD . /src


WORKDIR /src

ENV PROTOC_ZIP=protoc-3.13.0-linux-x86_64.zip
RUN apt-get update && apt-get install -y unzip
RUN curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/$PROTOC_ZIP \
    && unzip -o $PROTOC_ZIP -d /usr/local bin/protoc \
    && unzip -o $PROTOC_ZIP -d /usr/local 'include/*' \
    && rm -f $PROTOC_ZIP

RUN CGO_ENABLED=0 GOOS=linux make buildAllDockerMigration

WORKDIR /src/cmd

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./main .

ENTRYPOINT ["./main", "up"]
