// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: rpc/crm/v1/service.proto

package crmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddQuestionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Statement string `protobuf:"bytes,1,opt,name=statement,proto3" json:"statement,omitempty"`
	Option1   string `protobuf:"bytes,2,opt,name=option1,proto3" json:"option1,omitempty"`
	Option2   string `protobuf:"bytes,3,opt,name=option2,proto3" json:"option2,omitempty"`
	Option3   string `protobuf:"bytes,4,opt,name=option3,proto3" json:"option3,omitempty"`
	Option4   string `protobuf:"bytes,5,opt,name=option4,proto3" json:"option4,omitempty"`
	Answer    int32  `protobuf:"varint,6,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *AddQuestionRequest) Reset() {
	*x = AddQuestionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_crm_v1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQuestionRequest) ProtoMessage() {}

func (x *AddQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_crm_v1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQuestionRequest.ProtoReflect.Descriptor instead.
func (*AddQuestionRequest) Descriptor() ([]byte, []int) {
	return file_rpc_crm_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddQuestionRequest) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *AddQuestionRequest) GetOption1() string {
	if x != nil {
		return x.Option1
	}
	return ""
}

func (x *AddQuestionRequest) GetOption2() string {
	if x != nil {
		return x.Option2
	}
	return ""
}

func (x *AddQuestionRequest) GetOption3() string {
	if x != nil {
		return x.Option3
	}
	return ""
}

func (x *AddQuestionRequest) GetOption4() string {
	if x != nil {
		return x.Option4
	}
	return ""
}

func (x *AddQuestionRequest) GetAnswer() int32 {
	if x != nil {
		return x.Answer
	}
	return 0
}

type AddQuestionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AddQuestionResponse) Reset() {
	*x = AddQuestionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_crm_v1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQuestionResponse) ProtoMessage() {}

func (x *AddQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_crm_v1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQuestionResponse.ProtoReflect.Descriptor instead.
func (*AddQuestionResponse) Descriptor() ([]byte, []int) {
	return file_rpc_crm_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddQuestionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rpc_crm_v1_service_proto protoreflect.FileDescriptor

var file_rpc_crm_v1_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x72, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x72, 0x7a, 0x70, 0x2e,
	0x71, 0x75, 0x69, 0x7a, 0x2e, 0x63, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x22, 0xb2, 0x01, 0x0a, 0x12,
	0x41, 0x64, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x32, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x33, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x33, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x34, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x34, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x22, 0x2f, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x32, 0x66, 0x0a, 0x0a, 0x43, 0x72, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x58, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23,
	0x2e, 0x72, 0x7a, 0x70, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x63, 0x72, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x64, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x72, 0x7a, 0x70, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x63,
	0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x71, 0x75, 0x69,
	0x7a, 0x2f, 0x63, 0x72, 0x6d, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x72, 0x6d, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_crm_v1_service_proto_rawDescOnce sync.Once
	file_rpc_crm_v1_service_proto_rawDescData = file_rpc_crm_v1_service_proto_rawDesc
)

func file_rpc_crm_v1_service_proto_rawDescGZIP() []byte {
	file_rpc_crm_v1_service_proto_rawDescOnce.Do(func() {
		file_rpc_crm_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_crm_v1_service_proto_rawDescData)
	})
	return file_rpc_crm_v1_service_proto_rawDescData
}

var file_rpc_crm_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_crm_v1_service_proto_goTypes = []interface{}{
	(*AddQuestionRequest)(nil),  // 0: rzp.quiz.crm.v1.AddQuestionRequest
	(*AddQuestionResponse)(nil), // 1: rzp.quiz.crm.v1.AddQuestionResponse
}
var file_rpc_crm_v1_service_proto_depIdxs = []int32{
	0, // 0: rzp.quiz.crm.v1.CrmService.AddQuestion:input_type -> rzp.quiz.crm.v1.AddQuestionRequest
	1, // 1: rzp.quiz.crm.v1.CrmService.AddQuestion:output_type -> rzp.quiz.crm.v1.AddQuestionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_crm_v1_service_proto_init() }
func file_rpc_crm_v1_service_proto_init() {
	if File_rpc_crm_v1_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_crm_v1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddQuestionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_crm_v1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddQuestionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_crm_v1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_crm_v1_service_proto_goTypes,
		DependencyIndexes: file_rpc_crm_v1_service_proto_depIdxs,
		MessageInfos:      file_rpc_crm_v1_service_proto_msgTypes,
	}.Build()
	File_rpc_crm_v1_service_proto = out.File
	file_rpc_crm_v1_service_proto_rawDesc = nil
	file_rpc_crm_v1_service_proto_goTypes = nil
	file_rpc_crm_v1_service_proto_depIdxs = nil
}
